
name: Hyeid Admin Deployment

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@52.36.65.19 << 'EOF'
           cd /home/ec2-user/hyeid-admin
           git pull origin main
           npm ci
           npm run build
           pm2 restart hyeid-admin
          EOF
